CC=g++
CFLAGS=-c -Wall -std=c++11
LDFLAGS=

SOURCES=main.cpp \
	consumerProducerManager.cpp \
	application.cpp \

OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=task1

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@
